#!/usr/bin/env bash
# wallpaper folder

############## Main ################
SCRIPT=/home/xavier/Desktop/meow/colors/pywal16
GTK=/home/xavier/Desktop/meow/colors/oomox-gtk
WORKSPACES=/home/xavier/Desktop/meow/qof/wallpaper-per-workspace

############## SDDM ################
SDDM=/home/xavier/Desktop/conesque/sddm/wal.jpg
CACHE_SDDM=/home/xavier/Desktop/meow/colors/qml-sddm.py
WAL_SDDM=/home/xavier/Desktop/meow/colors/update-background

# Set the delimiter based on nsxiv configuration
[ "$NSXIV_USING_NULL" = 1 ] && DELIM='\0' || DELIM='\n'

while read file
do
	case "$1" in
#system
		"1") cp $file ~/Desktop/conesque/workspaces/1
		# hyprctl hyprpaper wallpaper 'eDP-1, /lien/Desktop/conesque/workspaces/1'
		wal -i $file -o $GTK
		awww imd --transition-type none --transition-duration 0.1 $file
#		awww img --transition-type wipe --transition-duration 1.0 --filter CatmullRom --transition-fps 78 --transition-angle 180 --transition-bezier .97,.03,.02,.98  $file 
				;;
#art
		"2") cp $file ~/Desktop/conesque/workspaces/2
				;;
#chill
		"3") cp $file ~/Desktop/conesque/workspaces/3
				;;
#clutter
		"4") cp $file ~/Desktop/conesque/workspaces/4
				;;
		"e") cp $file $SDDM
		python3 $CACHE_SDDM
		sudo $WAL_SDDM
				;;
esac
done
