#!/usr/bin/env bash

rm -rf ~/.themes/
pkill nemo
THEME_DIR="/lien/Desktop/meow/colors/theme_oomox/"
THEME="/lien/Desktop/meow/colors/theme_oomox/gtk-theme/change_color.sh"

nix develop "$THEME_DIR" -c "$THEME" ~/.cache/wal/colors-oomox 

/lien/Desktop/meow/colors/icons_numix/change_color.sh ~/.cache/wal/colors-oomox
nemo 
