# https://wiki.hypr.land/Configuring/Variables/#animations
animations { 
	enabled = yes, please :)

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
    bezier = fast, 0.97, 0.03, 0.02, 0.98
    bezier = custom, 0.48, 0.1, 0.52, 0.78
    bezier = easeOutQuint,0.23,1,0.32,1 
    bezier = easeInOutCubic,0.65,0.05,0.36,1 
    bezier = linear,0,0,1,1 
    bezier = almostLinear,0.5,0.5,0.75,1.0 
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 1, default 
    animation = border, 1, 1, easeOutQuint 
    animation = windows, 1, 1, fast
    animation = windowsIn, 0, 1.5, fast
    animation = windowsOut, 0, 0.5, fast
    animation = fadeIn, 0, 0.73, custom
    animation = fadeOut, 0, 1.46, custom
    animation = fade, 0, 1.03, linear
    animation = layers, 1, 1, easeOutQuint 
    animation = layersIn, 1, 1, easeOutQuint, fade 
    animation = layersOut, 1, 1, linear, fade 
    animation = fadeLayersIn, 1, 1.79, quick 
    animation = fadeLayersOut, 1, 1.39, quick
    animation = workspaces, 1, 1, fast, fade 
    animation = workspacesIn, 1, 1, fast, fade 
    animation = workspacesOut, 1, 1, fast, fade
}

