#system
$hyprregion = hyprshot -m region
$hyprwindow = hyprshot -m window
$terminal = kitty --working-directory / 
$fileManager = nemo 
$menu = rofi -modi 'drun,ssh' -show drun
$editor = kitty --working-directory / nvim

#ethernet
$browser = flatpak run io.gitlab.librewolf-community

#art 
$csp = dex ~/.local/share/applications/csp--CLIPStudioPaint--1774022681.052287.desktop
$ref = PureRef
$wal = /lien/Desktop/meow/colors/walmenu.sh
$music = spotify
$notes = kitty -e basalt
$rog = rog-control-center

#games
$anime = anime-game-launcher
$honkers = honkers-railway-launcher
$sleepy = sleepy-launcher



