# Autostart. Feel free to add your own entries.
# Shell components will be started in the includes.conf file, which we include below.
#
# All the settings below are up to you. We don't touch them in the shell config utility.
source = /lien/Desktop/meow/hypr/monitors.conf

#exec at start up and application
source = /lien/Desktop/meow/hypr/applications.conf
source = /lien/Desktop/meow/hypr/processes.conf

#appearence
source = /home/xavier/.cache/wal/colors-hyprland.conf
source = /lien/Desktop/meow/hypr/colors.conf
source = /lien/Desktop/meow/hypr/animations.conf

#layout and input
source = /lien/Desktop/meow/hypr/layinput.conf

#keybindings
source = /lien/Desktop/meow/hypr/keybindings.conf

#window and layer rules
source = /lien/Desktop/meow/hypr/winspace.conf
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
