##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more "Smart gaps" / "No gaps when only" uncomment all if you wish to use that. 
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
# workspace = w[tv1], gapsout:0, gapsin:0 workspace = f[1], gapsout:0, gapsin:0 
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1] 
# windowrule = rounding 0, floating:0, onworkspace:w[tv1] 
# windowrule = bordersize 0, floating:0, onworkspace:f[1] 
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# art
windowrule = float on,match:class PureRef
windowrule = pin on,match:class PureRef
windowrule = pin on,match:class Nsxiv 
windowrule = no_dim on,match:class PureRef
windowrule = opacity on,match:class PureRef 
windowrule = opaque on,match:class PureRef

# applications
#windowrule = float,class:^(librewolf)$,title:^(Picture-in-Picture)$
#windowrule = pin,class:^(librewolf)$,title:^(Picture-in-Picture)$
#windowrulev2 = fullscreen, class:(genshinimpact.exe), title:(Genshin Impact)

# system
#layerrule = blur,waybar
layerrule = blur on, match:namespace rofi 
layerrule = blur 20 3, match:namespace rofi
layerrule = blur_popups on, match:namespace rofi
layerrule = animation slide, match:namespace rofi
layerrule = blur on, match:namespace kitty
layerrule = blur 100 10, match:namespace kitty
layerrule = blur on, match:namespace quickshell


windowrule = opaque on, match:class cliptstudiopaint.exe
windowrule = fullscreen on, match:class clipstudiopaint.exe
#layerrule = ignorezero,rofi 
#layerrule = ignorealpha,rofi

# windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
#    name = suppress-maximize-events
#    match:class = .*

#    suppress_event = maximize
#}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

